sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
excludes:
  # Enable logging for Jsch
  - "E-PK-CORE-18: Outdated content: 'src/test/resources/logging.properties'"
build:
  exasolDbVersions:
    - "2026.1.0"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: setup-java
          content:
            name: Fix UDF VM Crashed error
            id: fix-udf-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
