sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
excludes:
  # Enable logging for Jsch
  - "E-PK-CORE-18: Outdated content: 'src/test/resources/logging.properties'"
build:
  exasolDbVersions:
    - "8.32.0"
    - "7.1.30"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix UDF VM Crashed error
            id: fix-udf-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        - action: REPLACE
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Run tests and build with Maven
            id: matrix-build
            run: |
              # Exclude cloud tests
              mvn --batch-mode clean verify -DexcludedGroups=cloudOnly \
                  -Dcom.exasol.dockerdb.image=${{ matrix.exasol_db_version }} \
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                  -DtrimStackTrace=false
