sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
      - lombok
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_prepare_original_checksum.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build-next-java.yml'"
linkReplacements:
  - "https://www.mojohaus.org/flatten-maven-plugin/flatten-maven-plugin|https://www.mojohaus.org/flatten-maven-plugin/"
  - "https://awhitford.github.com/lombok.maven/lombok-maven-plugin/|https://anthonywhitford.com/lombok.maven/lombok-maven-plugin/"
