name: CI Build

on:
  push:
  pull_request:
    types: [ opened ]
  issue_comment:
    types: [ created ]


jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
          echo "Stopping here since not enabled"
          exit 1
        if: steps.check.outputs.triggered != 'true'
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Enable Testconatiner reuse
        run: echo 'testcontainers.reuse.enable=true' >> "$HOME"/.testcontainers.properties
      - name: Create AWS test setup
        run: |
          terraform -chdir=cloudSetup/ init
          terraform -chdir=cloudSetup/ apply
          chmod 700 cloudSetup/generated/exasol_cluster_ssh_key
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run tests and build with Maven
        run: |
          . cloudSetup/generated/setEnv.sh
          mvn -B verify sonar:sonar --file pom.xml -Dsonar.organization=exasol -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Destroy cluster
        run: terraform -chdir=cloudSetup/ destroy
        if: always()