name: CI Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Enable Testconatiner reuse
        run: echo 'testcontainers.reuse.enable=true' >> "$HOME"/.testcontainers.properties
      - name: Run quick checks
        run: mvn -B verify --file pom.xml -DskipTests
      - name: Create AWS test setup
        run: |
          sudo apt-get install -y terrafrom
          terraform -chdir cloudSetup init
          terraform -chdir cloudSetup apply
          chmod 700 cloudSetup/generated/exasol_cluster_ssh_key
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run tests and build with Maven
        run: |
          . cloudSetup/generated/setEnv.sh
          mvn -B clean verify sonar:sonar --file pom.xml -Dsonar.organization=exasol -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Destroy cluster
        run: terraform destroy
        if: always()