name: CI Build Quick Checks
on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  quick-check-matrix-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.exasol_db_version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        exasol_db_version: [8.32.0, 7.1.30]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            11
            17
          cache: "maven"
      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Fix UDF VM Crashed error,
        id: fix-udf-vm-crash
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode clean verify \
              -Dcom.exasol.dockerdb.image=${{ matrix.exasol_db_version }} \
              -DexcludedGroups=cloudOnly

  quick-check-build:
    needs: quick-check-matrix-build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build successful"
