name: Quick Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quick-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            11
            17
          cache: "maven"
      - name: "Prepare container reuse"
        run: |
          echo 'testcontainers.reuse.enable=true' > "/home/runner/.testcontainers.properties"
      - name: Run quick checks
        run: mvn --batch-mode clean verify -DexcludedGroups=cloudOnly
