name: Quick Checks

on:
  - push

jobs:
  quick-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_db_version: ["7.1.23", "8.23.0"]
    env:
      DEFAULT_DB_VERSION: "7.1.23"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.docker_db_version }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"
      - name: "Prepare container reuse"
        run: |
          echo 'testcontainers.reuse.enable=true' > "/home/runner/.testcontainers.properties"
      - name: Run quick checks
        run: mvn --batch-mode clean verify -DexcludedGroups=cloudOnly -Dcom.exasol.dockerdb.image=${{ matrix.docker_db_version }}
